### ISSUE TITLE
evalute question

### ISSUE THREAD

**Issue by qn757275373** [chaowentao/SubFocal#1]
Hi, I use your checkpoint 'LF_checkpoint/SubFocal_sub_0.5_js_0.1_ckp/iter0010_valmse0.768_bp1.93.hdf5' to evaluate, but I cannot reach the accuracy in the paper, here is my result(badpixel 0.07):
backgammon:96.947
dots: 97.4974
pyramids: 97.7432
stripes: 97.5043
boxes:97.0235
cotton:98.0419
dino: 97.4948
sideboard: 98.3075

**Comment by chaowentao** [comment]
> Hi, I use your checkpoint 'LF_checkpoint/SubFocal_sub_0.5_js_0.1_ckp/iter0010_valmse0.768_bp1.93.hdf5' to evaluate, but I cannot reach the accuracy in the paper, here is my result(badpixel 0.07): backgammon:96.947 dots: 97.4974 pyramids: 97.7432 stripes: 97.5043 boxes:97.0235 cotton:98.0419 dino: 97.4948 sideboard: 98.3075

OK, please provide more details and what the mean about the your resluts. why it so large?

**Comment by qn757275373** [comment]
> > Hi, I use your checkpoint 'LF_checkpoint/SubFocal_sub_0.5_js_0.1_ckp/iter0010_valmse0.768_bp1.93.hdf5' to evaluate, but I cannot reach the accuracy in the paper, here is my result(badpixel 0.07): backgammon:96.947 dots: 97.4974 pyramids: 97.7432 stripes: 97.5043 boxes:97.0235 cotton:98.0419 dino: 97.4948 sideboard: 98.3075
> 
> OK, please provide more details and what the mean about the your resluts. why it so large?

Thanks，It may be that there is a problem with the uploading of the ckpt file, and it will be OK to download it again
