### ISSUE TITLE
关于4D LF benchmark数据集的问题 

### ISSUE THREAD

**Issue by PPXGS** [chaowentao/SubFocal#2]
你好，师兄。能问您一个问题吗？关于4D LF benchmark数据集的其中的test文件下的bedroom,bicycle,herbs,origami四个场景gt的pfm文件怎么获得呢？如果没获取的话，那些bp007和mse指标怎么计算得到的呢？

**Comment by chaowentao** [comment]
我们获取不到test场景的gt，只能把自己的预测结果在网站上提交，官方会给出评测结果

**Comment by PPXGS** [comment]
原来是这样，谢谢师兄！我的方向也是光场深度估计，后续也想发TCI。觉得比较巧，能要一下您的邮箱吗？方便后续一起讨论问题。

**Comment by PPXGS** [comment]
或者师兄不方便在公共平台透露的话，我的邮箱是1223252875@qq.com。师兄到时候可以滴滴我一下。

**Comment by PPXGS** [comment]
谢谢师兄的回复






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaowentao/SubFocal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月17日(星期五) 晚上8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chaowentao/SubFocal] 关于4D LF benchmark数据集的问题  (Issue #2)





 
我们获取不到test场景的gt，只能把自己的预测结果在网站上提交，官方会给出评测结果

**Comment by chaowentao** [comment]
没事，我的邮箱是chaowentao@mail.bnu.edu.cn，欢迎后续一起交流讨论

**Comment by PPXGS** [comment]
好的，谢谢！
